version: "3"
services:
  config:
    build: Limits-Spring-Cloud-Config-Server/
    ports:
      - "8888:8888"
    links:
      - eureka
    depends_on:
      - eureka
    networks:
     - spring_cloud_network
  eureka:
    build: Netlifx-Eureka-Naming-Server/
    ports:
      - "8761:8761"
    networks:
      - spring_cloud_network
  zuul:
    build: ./Netlifx-Zuul-Api-Gateway
    ports:
      - "8765:8765"
    links:
      - eureka
    networks:
      - spring_cloud_network
  limits:
      build: ./Limits-Service
      ports:
        - "8080:8080"
      depends_on:
        - config
      links:
        - config
      networks:
        - spring_cloud_network
  exchange:
    build: ./Limits-Currency-Exchange-Service
    ports:
      - "8001:8001"
    links:
      - limits
      - config
    networks:
      - spring_cloud_network
  calculation:
    build: ./Limits-Currency-Calculation-Service
    ports:
      - "8100:8100"
    links:
      - exchange
      - config
    networks:
      - spring_cloud_network

networks:
  spring_cloud_network:
    external: true
